### ISSUE TITLE
character "6" is not sent in cw from keyboard 

### ISSUE THREAD

**Issue by g6zbv** [afarhan/sbitx#59] opened 2023-11-14 04:39 UTC
character "6" is not sent in cw from keyboard

**Comment by mbridak** [comment] 2023-11-14 14:12
I'm sorry, I can't reproduce this.

**Comment by g6zbv** [comment] 2023-11-14 16:15
Hi

I think you’ll find it sends “H” instead its missing the first dash


Cheers

Adrian

**Comment by MolKa51** [comment] 2023-11-17 07:46
Adrian,
in the BITX20 group, in post #104223, this bug has been fixed, which is in use with v2 sBitx. In the above message, a typo occurred in the modem.c file. If you use v3, it is fixed there and you can find the fix in the modem_cw.c file.

**Comment by afarhan** [comment] 2024-01-19 06:31
This is fixed in v3

**Closed by afarhan** 2024-01-19 06:31 UTC
